var CLASS = [{"name":"Hierophant","attribute":["str","int"],"tag":[]},
{"name":"Inquisitor","attribute":["str","int"],"tag":[]},
{"name":"Guardian","attribute":["str","int"],"tag":[]},
{"name":"Necromancer","attribute":["int"],"tag":[]},
{"name":"Elementalist","attribute":["int"],"tag":[]},
{"name":"Occultist","attribute":["int"],"tag":[]},
{"name":"Saboteur","attribute":["int","dex"],"tag":[]},
{"name":"Assassin","attribute":["int","dex"],"tag":[]},
{"name":"Trickster","attribute":["int","dex"],"tag":[]},
{"name":"Raider","attribute":["dex"],"tag":[]},
{"name":"Deadeye","attribute":["dex"],"tag":[]},
{"name":"Pathfinder","attribute":["dex"],"tag":[]},
{"name":"Slayer","attribute":["dex","str"],"tag":[]},
{"name":"Champion","attribute":["dex","str"],"tag":[]},
{"name":"Gladiator","attribute":["dex","str"],"tag":[]},
{"name":"Chieftain","attribute":["str"],"tag":[]},
{"name":"Juggernaut","attribute":["str"],"tag":[]},
{"name":"Berserker","attribute":["str"],"tag":[]},
{"name":"Ascendant","attribute":["str","int","dex"],"tag":[]}];

var TAG=[{"name":"Construct","level":1,"weight":100,"subtag":["Trap", "Mine", "Totem"],"exclusion":[]},
{"name":"Summoner","level":1,"weight":100,"subtag":["Bodyguard", "Aides", "Army", "Unique"],"exclusion":[]},
{"name":"Duration","level":1,"weight":100,"subtag":["Corruption", "Shiver", "Burn", "Bleed"],"exclusion":[]},
{"name":"Melee","level":1,"weight":100,"subtag":["One handed", "Dual", "Two handed", "Type"],"exclusion":[]},
{"name":"Caster","level":1,"weight":100,"subtag":["Pure", "Convertion", "Mixed"],"exclusion":[]},
{"name":"Triggered","level":1,"weight":100,"subtag":["Chanel", "Crit", "Slinger", "Unique", "Type"],"exclusion":[]},
{"name":"Ranged","level":1,"weight":100,"subtag":["Bow", "Wand", "Shield", "Weapon", "Type"],"exclusion":[]},
{"name":"Support","level":1,"weight":100,"subtag":["Aura", "Curse", "Mana", "Warcry", "Unique"],"exclusion":[]},
{"name":"Trap","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Mine","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Totem","level":2,"weight":100,"subtag":["Caster", "Ranged", "Melee"],"exclusion":["Shield"]},
{"name":"Bodyguard","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Aides","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Army","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Corruption","level":2,"weight":100,"subtag":["Caster", "Bow", "Chaos", "Ailment"],"exclusion":[]},
{"name":"Shiver","level":2,"weight":100,"subtag":["Cold"],"exclusion":[]},
{"name":"Burn","level":2,"weight":100,"subtag":["Fire", "Ailment"],"exclusion":[]},
{"name":"Bleed","level":2,"weight":100,"subtag":["Physical", "Ailment"],"exclusion":[]},
{"name":"One handed","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Dual","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Two handed","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Pure","level":2,"weight":100,"subtag":["Type"],"exclusion":[]},
{"name":"Conversion","level":2,"weight":100,"subtag":["Type"],"exclusion":["Physical"]},
{"name":"Mixed","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Chanel","level":2,"weight":100,"subtag":["Type"],"exclusion":[]},
{"name":"Crit","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Slinger","level":2,"weight":100,"subtag":["Caster"],"exclusion":["Selfcast"]},
{"name":"Bow","level":2,"weight":100,"subtag":["Type"],"exclusion":[]},
{"name":"Wand","level":2,"weight":100,"subtag":["Type"],"exclusion":[]},
{"name":"Shield","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Weapon","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Aura","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Curse","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Mana","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Warcry","level":2,"weight":100,"subtag":[],"exclusion":[]},
{"name":"Type","level":3,"weight":100,"subtag":["Lightning", "Fire", "Cold", "Physical", "Chaos"],"exclusion":[]},
{"name":"Ailment","level":3,"weight":100,"subtag":[],"exclusion":[]}];

var GEM=[{"name":"Leap Slam","attribute":"str","tag":["Movement"," Melee"]},
{"name":"Sweep","attribute":"str","tag":["Two handed"]},
{"name":"Ground Slam","attribute":"str","tag":["Melee"]},
{"name":"Cleave","attribute":"str","tag":["Melee"]},
{"name":"Shield Charge","attribute":"str","tag":["Shield"]},
{"name":"Enduring Cry","attribute":"str","tag":["Warcry"]},
{"name":"Immortal Call","attribute":"str","tag":["Defense"]},
{"name":"Infernal Blow","attribute":"str","tag":["Melee"," Fire"]},
{"name":"Glacial Hammer","attribute":"str","tag":["Melee"," Cold"]},
{"name":"Warlord's Mark","attribute":"str","tag":["Curse"]},
{"name":"Punishment","attribute":"str","tag":["Curse"]},
{"name":"Heavy Strike","attribute":"str","tag":["Melee"]},
{"name":"Dominating Blow","attribute":"str","tag":["Army"]},
{"name":"Molten Shell","attribute":"str","tag":["Defense"]},
{"name":"Vitality","attribute":"str","tag":["Aura"]},
{"name":"Determination","attribute":"str","tag":["Aura"]},
{"name":"Anger","attribute":"str","tag":["Aura"]},
{"name":"Shockwave Totem","attribute":"str","tag":["Totem"," Caster"," Physical"]},
{"name":"Rejuvenation Totem","attribute":"str","tag":["Defense"]},
{"name":"Decoy Totem","attribute":"str","tag":["Defense"]},
{"name":"Devouring Totem","attribute":"str","tag":["Defense"]},
{"name":"Holy Flame Totem","attribute":"str","tag":["Totem"," Caster"," Conversion"," Fire"]},
{"name":"Searing Bond","attribute":"str","tag":["Totem"," Burn"]},
{"name":"Animate Guardian","attribute":"str","tag":["Aides"]},
{"name":"Purity of Fire","attribute":"str","tag":["Aura"]},
{"name":"Molten Strike","attribute":"str","tag":["Melee"]},
{"name":"Herald of Ash","attribute":"str","tag":["Burn"]},
{"name":"Herald of Purity","attribute":"str","tag":["Aides"]},
{"name":"Reckoning","attribute":"str","tag":["Defense"]},
{"name":"Static Strike","attribute":"str","tag":["Melee"]},
{"name":"Vengeance","attribute":"str","tag":["Defense"]},
{"name":"Summon Flame Golem","attribute":"str","tag":["Aides"]},
{"name":"Ice Crash","attribute":"str","tag":["Melee"]},
{"name":"Rallying Cry","attribute":"str","tag":["Warcry"]},
{"name":"Abyssal Cry","attribute":"str","tag":["Warcry"]},
{"name":"Vigilant Strike","attribute":"str","tag":["Melee"]},
{"name":"Summon Stone Golem","attribute":"str","tag":["Aides"]},
{"name":"Earthquake","attribute":"str","tag":["Melee"]},
{"name":"Ancestral Protector","attribute":"str","tag":["Totem"," Melee"]},
{"name":"Ancestral Warchief","attribute":"str","tag":["Totem"," Melee"]},
{"name":"Sunder","attribute":"str","tag":["Melee"]},
{"name":"Tectonic Slam","attribute":"str","tag":["Melee"]},
{"name":"Vulnerability","attribute":"str","tag":["Curse"]},
{"name":"Consecrated Path","attribute":"str","tag":["Melee"]},
{"name":"Smite","attribute":"str","tag":["Melee"," Lightning"]},
{"name":"War Banner","attribute":"str","tag":["Aura"]},
{"name":"Dread Banner","attribute":"str","tag":["Aura"]},
{"name":"Steelskin","attribute":"str","tag":["Defense"]},
{"name":"Bladestorm","attribute":"str","tag":["Melee"]},
{"name":"Blood and Sand","attribute":"str","tag":["Defense"]},
{"name":"Berserk","attribute":"str","tag":["Defense"]},
{"name":"Perforate","attribute":"str","tag":["Melee"]},
{"name":"Chain Hook","attribute":"str","tag":["Melee"]},
{"name":"Flesh and Stone","attribute":"str","tag":["Defense"]},
{"name":"Pride","attribute":"str","tag":["Aura"]},
{"name":"Charged Dash","attribute":"dex","tag":["Melee"," Chanel"]},
{"name":"Blade Flurry","attribute":"dex","tag":["Melee"]},
{"name":"Double Strike","attribute":"dex","tag":["Melee"]},
{"name":"Lacerate","attribute":"dex","tag":["Melee"]},
{"name":"Elemental Hit","attribute":"dex","tag":["Melee"," Bow"," Wand"]},
{"name":"Dual Strike","attribute":"dex","tag":["Dual"]},
{"name":"Whirling Blades","attribute":"dex","tag":["Movement"," Melee"]},
{"name":"Frenzy","attribute":"dex","tag":["Melee"," Bow"," Wand"]},
{"name":"Detonate Dead","attribute":"dex","tag":["Caster"," Fire"]},
{"name":"Volatile Dead","attribute":"dex","tag":["Caster"," Fire"]},
{"name":"Unearth","attribute":"dex","tag":["Caster"," Physical"," Army"]},
{"name":"Split Arrow","attribute":"dex","tag":["Bow"]},
{"name":"Caustic Arrow","attribute":"dex","tag":["Bow"," Corruption"]},
{"name":"Blood Rage","attribute":"dex","tag":["Defense"]},
{"name":"Flicker Strike","attribute":"dex","tag":["Melee"]},
{"name":"Viper Strike","attribute":"dex","tag":["Melee"," Ailment"]},
{"name":"Phase Run","attribute":"dex","tag":["Movement"]},
{"name":"Explosive Arrow","attribute":"dex","tag":["Bow"," Fire"]},
{"name":"Temporal Chains","attribute":"dex","tag":["Curse"]},
{"name":"Projectile Weakness","attribute":"dex","tag":["Curse"]},
{"name":"Rain of Arrows","attribute":"dex","tag":["Bow"]},
{"name":"Lightning Strike","attribute":"dex","tag":["Melee"]},
{"name":"Puncture","attribute":"dex","tag":["Melee"," Bleed"," Bow"]},
{"name":"Lightning Arrow","attribute":"dex","tag":["Bow"]},
{"name":"Haste","attribute":"dex","tag":["Aura"]},
{"name":"Grace","attribute":"dex","tag":["Aura"]},
{"name":"Hatred","attribute":"dex","tag":["Aura"]},
{"name":"Burning Arrow","attribute":"dex","tag":["Bow"]},
{"name":"Bear Trap","attribute":"dex","tag":["Trap"," Physical"]},
{"name":"Fire Trap","attribute":"dex","tag":["Trap"," Fire"," Caster"]},
{"name":"Ethereal Knives","attribute":"dex","tag":["Caster"," Physical"]},
{"name":"Ice Shot","attribute":"dex","tag":["Bow"]},
{"name":"Arctic Armour","attribute":"dex","tag":["Defense"]},
{"name":"Cyclone","attribute":"dex","tag":["Chanel"," Melee"]},
{"name":"Reave","attribute":"dex","tag":["Melee"]},
{"name":"Smoke Mine","attribute":"dex","tag":["Movement"]},
{"name":"Spectral Shield Throw","attribute":"dex","tag":["Shield"]},
{"name":"Spectral Throw","attribute":"dex","tag":["Melee"]},
{"name":"Animate Weapon","attribute":"dex","tag":["Army"]},
{"name":"Purity of Ice","attribute":"dex","tag":["Aura"]},
{"name":"Barrage","attribute":"dex","tag":["Bow"," Wand"]},
{"name":"Desecrate","attribute":"dex","tag":["Defense"]},
{"name":"Tornado Shot","attribute":"dex","tag":["Bow"]},
{"name":"Herald of Ice","attribute":"dex","tag":["Defense"]},
{"name":"Herald of Agony","attribute":"dex","tag":["Aides"]},
{"name":"Poacher's Mark","attribute":"dex","tag":["Curse"]},
{"name":"Blink Arrow","attribute":"dex","tag":["Movement"]},
{"name":"Mirror Arrow","attribute":"dex","tag":["Aides"]},
{"name":"Riposte","attribute":"dex","tag":["Defense"]},
{"name":"Summon Ice Golem","attribute":"dex","tag":["Aides"]},
{"name":"Frost Blades","attribute":"dex","tag":["Melee"]},
{"name":"Wild Strike","attribute":"dex","tag":["Melee"]},
{"name":"Ice Trap","attribute":"dex","tag":["Trap"," Cold"," Caster"]},
{"name":"Blast Rain","attribute":"dex","tag":["Bow"]},
{"name":"Galvanic Arrow","attribute":"dex","tag":["Bow"]},
{"name":"Bladefall","attribute":"dex","tag":["Caster"," Physical"]},
{"name":"Blade Vortex","attribute":"dex","tag":["Caster"," Physical"]},
{"name":"Siege Ballista","attribute":"dex","tag":["Bow"]},
{"name":"Cremation","attribute":"dex","tag":["Caster"," Fire"]},
{"name":"Explosive Trap","attribute":"dex","tag":["Trap"," Conversion"," Caster"]},
{"name":"Flamethrower Trap","attribute":"dex","tag":["Trap"," Fire"," Caster"]},
{"name":"Seismic Trap","attribute":"dex","tag":["Trap"," Physical"," Caster"]},
{"name":"Scourge Arrow","attribute":"dex","tag":["Bow"]},
{"name":"Toxic Rain","attribute":"dex","tag":["Bow"," Corruption"]},
{"name":"Lancing Steel","attribute":"dex","tag":["Melee"]},
{"name":"Shattering Steel","attribute":"dex","tag":["Melee"]},
{"name":"Dash","attribute":"dex","tag":["Movement"]},
{"name":"Precision","attribute":"dex","tag":["Aura"]},
{"name":"Cobra Lash","attribute":"dex","tag":["Melee"]},
{"name":"Withering Step","attribute":"dex","tag":["Movement"]},
{"name":"Plague Bearer","attribute":"dex","tag":["Defense"]},
{"name":"Pestilent Strike","attribute":"dex","tag":["Melee"," Corruption"]},
{"name":"Venom Gyre","attribute":"dex","tag":["Melee"]},
{"name":"Shrapnel Ballista","attribute":"dex","tag":["Bow"," Totem"]},
{"name":"Ensnaring Arrow","attribute":"dex","tag":["Bow"]},
{"name":"Artillery Ballista","attribute":"dex","tag":["Bow"," Totem"]},
{"name":"Blade Blast","attribute":"dex","tag":["Caster"," Physical"]},
{"name":"Fireball","attribute":"int","tag":["Caster"," Fire"]},
{"name":"Ice Nova","attribute":"int","tag":["Caster"," Cold"]},
{"name":"Cold Snap","attribute":"int","tag":["Shiver"]},
{"name":"Raise Zombie","attribute":"int","tag":["Bodyguard"]},
{"name":"Righteous Fire","attribute":"int","tag":["Burn"]},
{"name":"Discharge","attribute":"int","tag":["Caster"," Mixed"]},
{"name":"Spark","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Ice Spear","attribute":"int","tag":["Caster"," Cold"]},
{"name":"Raise Spectre","attribute":"int","tag":["Bodyguard"]},
{"name":"Frost Wall","attribute":"int","tag":["Defense"]},
{"name":"Freezing Pulse","attribute":"int","tag":["Caster"," Cold"]},
{"name":"Shock Nova","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Elemental Weakness","attribute":"int","tag":["Curse"]},
{"name":"Enfeeble","attribute":"int","tag":["Curse"]},
{"name":"Assassin's Mark","attribute":"int","tag":["Curse"]},
{"name":"Despair","attribute":"int","tag":["Curse"]},
{"name":"Lightning Warp","attribute":"int","tag":["Movement"]},
{"name":"Summon Skeletons","attribute":"int","tag":["Army"]},
{"name":"Firestorm","attribute":"int","tag":["Caster"," Fire"]},
{"name":"Tempest Shield","attribute":"int","tag":["Defense"]},
{"name":"Power Siphon","attribute":"int","tag":["Wand"]},
{"name":"Purity of Elements","attribute":"int","tag":["Aura"]},
{"name":"Discipline","attribute":"int","tag":["Aura"]},
{"name":"Wrath","attribute":"int","tag":["Aura"]},
{"name":"Clarity","attribute":"int","tag":["Aura"]},
{"name":"Icicle Mine","attribute":"int","tag":["Mine"," Cold"," Caster"]},
{"name":"Conversion Trap","attribute":"int","tag":["Trap"," Aides"]},
{"name":"Arctic Breath","attribute":"int","tag":["Shiver"]},
{"name":"Arc","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Flammability","attribute":"int","tag":["Curse"]},
{"name":"Frostbite","attribute":"int","tag":["Curse"]},
{"name":"Conductivity","attribute":"int","tag":["Curse"]},
{"name":"Storm Burst","attribute":"int","tag":["Caster"," Lightning"," Conversion"," Chanel"]},
{"name":"Incinerate","attribute":"int","tag":["Caster"," Fire"," Channel"]},
{"name":"Lightning Trap","attribute":"int","tag":["Trap"," Lightning"," Caster"]},
{"name":"Purity of Lightning","attribute":"int","tag":["Aura"]},
{"name":"Storm Call","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Flameblast","attribute":"int","tag":["Caster"," Fire"," Channel"]},
{"name":"Ball Lightning","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Summon Raging Spirit","attribute":"int","tag":["Army"]},
{"name":"Flame Surge","attribute":"int","tag":["Caster"," Fire"]},
{"name":"Flesh Offering","attribute":"int","tag":["Defense"]},
{"name":"Bone Offering","attribute":"int","tag":["Defense"]},
{"name":"Spirit Offering","attribute":"int","tag":["Defense"]},
{"name":"Glacial Cascade","attribute":"int","tag":["Caster"," Cold"," Conversion"]},
{"name":"Convocation","attribute":"int","tag":["Defense"]},
{"name":"Pyroclast Mine","attribute":"int","tag":["Mine"," Fire"," Caster"]},
{"name":"Herald of Thunder","attribute":"int","tag":["Defense"]},
{"name":"Lightning Tendrils","attribute":"int","tag":["Caster"," Lightning"," Chanel"]},
{"name":"Kinetic Blast","attribute":"int","tag":["Wand"]},
{"name":"Summon Chaos Golem","attribute":"int","tag":["Aides"]},
{"name":"Summon Lightning Golem","attribute":"int","tag":["Aides"]},
{"name":"Flame Dash","attribute":"int","tag":["Movement"]},
{"name":"Magma Orb","attribute":"int","tag":["Caster"," Fire"]},
{"name":"Frost Bomb","attribute":"int","tag":["Defense"]},
{"name":"Orb of Storms","attribute":"int","tag":["Defense"]},
{"name":"Contagion","attribute":"int","tag":["Defense"]},
{"name":"Wither","attribute":"int","tag":["Corruption"]},
{"name":"Blight","attribute":"int","tag":["Corruption"]},
{"name":"Essence Drain","attribute":"int","tag":["Corruption"]},
{"name":"Frostbolt","attribute":"int","tag":["Caster"," Cold"]},
{"name":"Vortex","attribute":"int","tag":["Shiver"]},
{"name":"Dark Pact","attribute":"int","tag":["Caster"," Chaos"]},
{"name":"Scorching Ray","attribute":"int","tag":["Caster"," Burning"," Chanel"]},
{"name":"Bodyswap","attribute":"int","tag":["Caster"," Fire"]},
{"name":"Siphoning Trap","attribute":"int","tag":["Trap"," Shiver"," Caster"]},
{"name":"Lightning Spire Trap","attribute":"int","tag":["Trap"," Lightning"," Caster"]},
{"name":"Summon Holy Relic","attribute":"int","tag":["Defense"]},
{"name":"Winter Orb","attribute":"int","tag":["Caster"," Cold"," Chanel"]},
{"name":"Storm Brand","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Armageddon Brand","attribute":"int","tag":["Caster"," Fire"]},
{"name":"Brand Recall","attribute":"int","tag":["Defense"]},
{"name":"Purifying Flame","attribute":"int","tag":["Caster"," Fire"," Conversion"]},
{"name":"Soulrend","attribute":"int","tag":["Corruption"]},
{"name":"Bane","attribute":"int","tag":["Corruption"]},
{"name":"Wave of Conviction","attribute":"int","tag":["Caster"," Mixed"]},
{"name":"Zealotry","attribute":"int","tag":["Aura"]},
{"name":"Divine Ire","attribute":"int","tag":["Caster"," Conversion"," Lightning"," Chanel"]},
{"name":"Malevolence","attribute":"int","tag":["Aura"]},
{"name":"Frostblink","attribute":"int","tag":["Movement"]},
{"name":"Summon Carrion Golem","attribute":"int","tag":["Aides"]},
{"name":"Stormblast Mine","attribute":"int","tag":["Mine"," Lightning"," Caster"]},
{"name":"Summon Skitterbots","attribute":"int","tag":["Aura"]},
{"name":"Arcane Cloak","attribute":"int","tag":["Defense"]},
{"name":"Stormbind","attribute":"int","tag":["Caster"," Lightning"]},
{"name":"Kinetic Bolt","attribute":"int","tag":["Wand"]}];

var KEYSTONE=[{"name":"Blank","isunique":"no","weight":100,"require":[],"exclusion":[]},
{"name":"Phase Acrobatics","isunique":"no","weight":5,"require":["Dex"],"exclusion":[]},
{"name":"Ancestral Bond","isunique":"no","weight":5,"require":["Totem"],"exclusion":[]},
{"name":"Avatar of Fire","isunique":"no","weight":5,"require":["Conversion"],"exclusion":["Chaos"]},
{"name":"Blood Magic","isunique":"no","weight":5,"require":["Str"],"exclusion":[]},
{"name":"Chaos Inoculation","isunique":"no","weight":5,"require":["Int"],"exclusion":[]},
{"name":"Eldritch Battery","isunique":"no","weight":5,"require":[],"exclusion":["Str"]},
{"name":"Elemental Equilibrium","isunique":"no","weight":5,"require":["Duration"],"exclusion":["Corruption"," Bleed"]},
{"name":"Elemental Overload","isunique":"no","weight":5,"require":["Fire"," Cold"," Lightning"],"exclusion":[]},
{"name":"Ghost Reaver","isunique":"no","weight":5,"require":[],"exclusion":["Duration"," Ailment"]},
{"name":"Iron Grip","isunique":"no","weight":5,"require":["Ranged"],"exclusion":["Int"]},
{"name":"Mind over Matter","isunique":"no","weight":5,"require":[],"exclusion":["Dex"]},
{"name":"Minion Instability","isunique":"no","weight":5,"require":["Army"],"exclusion":[]},
{"name":"Perfect Agony","isunique":"no","weight":5,"require":["Ailment"],"exclusion":[]},
{"name":"Point Blank","isunique":"no","weight":5,"require":["Ranged"],"exclusion":[]},
{"name":"Resolute Technique","isunique":"no","weight":5,"require":["Melee"],"exclusion":[]},
{"name":"Unwavering Stance","isunique":"no","weight":5,"require":["Str"],"exclusion":[]},
{"name":"Vaal Pact","isunique":"no","weight":5,"require":[],"exclusion":["Duration"," Ailment"]},
{"name":"Wicked Ward","isunique":"no","weight":5,"require":["Int"],"exclusion":[]},
{"name":"Divine Flesh","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Eternal Youth","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Corrupted Soul","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Strength of Blood","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Tempered by War","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Glancing Blows","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Wind Dancer","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Dance with Death","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Second Sight","isunique":"yes","weight":2,"require":["Melee"],"exclusion":[]},
{"name":"The Agnostic","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Inner Conviction","isunique":"yes","weight":2,"require":["Caster"],"exclusion":[]},
{"name":"Power of Purpose","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Supreme Decadence","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Supreme Grandstanding","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Supreme Ego","isunique":"yes","weight":2,"require":[],"exclusion":[]},
{"name":"Disciple of Kitava","isunique":"yes","weight":3,"require":[],"exclusion":[]},
{"name":"Lone Messenger","isunique":"yes","weight":3,"require":[],"exclusion":[]},
{"name":"Nature's Patience","isunique":"yes","weight":3,"require":[],"exclusion":["Duration"," Ailment"]},
{"name":"Secrets of Suffering","isunique":"yes","weight":3,"require":["Cold"," Lightning"," Fire"],"exclusion":[]},
{"name":"Kineticism","isunique":"yes","weight":3,"require":["Ranged"," Bleed"],"exclusion":["Caster"]},
{"name":"Veteran's Awareness","isunique":"yes","weight":3,"require":[],"exclusion":[]},
{"name":"Hollow Palm Technique","isunique":"yes","weight":1,"require":["Dual"],"exclusion":[]}];

var isIncludeMovement=false;
var isIncludeDefense=false;
var isIncludeUnique=false;

function shuffle(a) {
    var j, x, i;
    for (i = a.length; i; i--) {
        j = Math.floor(Math.random() * i);
        x = a[i - 1];
        a[i - 1] = a[j];
        a[j] = x;
    }
}

function spin() {
  shuffle(KEYSTONE);
  shuffle(CLASS);
  shuffle(GEM);
  var randomKeystones = KEYSTONE.slice(0, 5);
  var randomClass = CLASS.slice(0, 5);
  var randomGem = GEM.filter(g => (!g.tag.includes("Defense") || isIncludeDefense) && (!g.tag.includes("Movement") || isIncludeMovement) && (!g.isUnique || isIncludeUnique)).slice(0, 5);
  
  var html = "<table><tr><td>keystone</td><td>Class</td><td>Gem</td></tr><tr><td>"+randomKeystones[0].name+"</td><td>"+randomClass[0].name+"</td><td>"+randomGem[0].name+"</td></tr><tr><td>"+randomKeystones[1].name+"</td><td>"+randomClass[1].name+"</td><td>"+randomGem[1].name+"</td></tr><tr><td>"+randomKeystones[2].name+"</td><td>"+randomClass[2].name+"</td><td>"+randomGem[2].name+"</td></tr><tr><td>"+randomKeystones[3].name+"</td><td>"+randomClass[3].name+"</td><td>"+randomGem[3].name+"</td></tr><tr><td>"+randomKeystones[4].name+"</td><td>"+randomClass[4].name+"</td><td>"+randomGem[4].name+"</td></tr>";
  
  var div = document.getElementById("maindiv");
  div.innerHTML = html;
  
};


